name: "analyze"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'fixtures/**'
      - '**.md'
  schedule:
    - cron: '34 10 * * 2'

jobs:
  cancel-previous-runs:
    name: Cancel previous runs
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[skip ci]') && !contains(github.event.commits[0].message, '[ci skip]')"
    steps:
      - uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[skip ci]') && !contains(github.event.commits[0].message, '[ci skip]')"
    needs: cancel-previous-runs
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'go' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
      if: ${{ matrix.language == 'go' }}

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: ${{ matrix.language }}
      timeout-minutes: 10

    - name: Autobuild
      uses: github/codeql-action/autobuild@v4
      if: ${{ matrix.language != 'go' }}
      timeout-minutes: 30

    - name: Install deps for capture
      run: |
        sudo apt-get install software-properties-common wget
        sudo add-apt-repository universe
        wget https://packages.ntop.org/apt-stable/22.04/all/apt-ntop-stable.deb
        sudo apt install ./apt-ntop-stable.deb
        sudo apt update
        sudo apt install -y libpcap-dev pfring
      if: ${{ matrix.language == 'go' }}

    - name: Lint
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        golangci-lint run
      if: ${{ matrix.language == 'go' }}

    - name: Test
      run: |
        go test ./... -race -coverprofile=coverage.out -covermode=atomic
      if: ${{ matrix.language == 'go' }}

    - name: Build microservice
      run: |
        make build
      if: ${{ matrix.language == 'go' }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v4
      with:
        category: "/language:${{matrix.language}}"